#!/bin/zsh

function goto_repo() {
  [[ $(pwd) == "${APP_DIR}" ]] && return 0
  cd ${APP_DIR}
  [[ -r .rvmrc ]] && source .rvmrc
}

function current_branch() {
  basename $(git symbolic-ref HEAD)
}

function app_name() {
  git remote -v | grep "^[^[:space:]]*${1}[^[:space:]]*[[:space:]]" | sed 's/.*://;s/\.git.*//' | head -1
}

case $1 in
  '')
    echo $APP_DIR
  ;;

  -edit | --edit) vim $0 ;;

  dir) echo $APP_DIR ;;

  egit) goto_repo; vim .git/config ;;

  git) goto_repo; cat .git/config ;;

  remotes) goto_repo; git remote -v ;;

  logs | log | l)
    goto_repo

    [[ -z "$2" ]] && exit 1
    heroku logs -t -a $(app_name "$2")
  ;;

  console | con | c)
    goto_repo

    [[ -z "$2" ]] && script/rails console && exit
    heroku run rails console -a $(app_name "$2")
  ;;

  psql | pg | p)
    goto_repo

    [[ -z "$2" ]] && psql ${APP_NAME}_development && exit
    heroku pg:psql -a $(app_name "$2")
  ;;

  origin)
    git push origin head
  ;;

  deploy | d)
    goto_repo

    [[ -z "$2" ]] && echo 'A <remote> is required when deploying.' && exit
    git push "$2" head
    $0 migrate "$2"
    $0 restart "$2"
  ;;

  restart | r)
    goto_repo

    [[ -z "$2" ]] && echo 'A <remote> is required when restarting.' && exit
    heroku restart -a $(app_name "$2")
  ;;

  migrate | m)
    goto_repo

    [[ -z "$2" ]] && rake db:migrate && exit
    heroku run rake db:migrate -a $(app_name "$2")
  ;;

  -e)
    cd ~/lists
    args=()
    for i ({2..$#@}) args[$(( $i - 1 ))]="apps/${APP_NAME}/$@[$i]"

    echo "Make any missing directories"
    for f ($args) mkdir -pv $(dirname $f)
    vim -O $args
  ;;

  *)
    cat <<NOTES
    ERROR: UNKNOWN COMMAND
    ERROR: UNKNOWN COMMAND

      USAGE: ${APP_NAME} <command> [*args = <remote> | <file>]

      What should the default behavior be?
        cd to ${APP_DIR}?

      Commands
        <no cmd> | dir      Show the directory where the app is located
        -e                  Create or edit notes for this app
        -edit | --edit      Edit this file: base-binstub
        egit                Edit the .git/config file
        git                 Show the .git/config file
        remotes             List all configured remote repos
        logs | log | l      Tail the heroku server logs
        console | con | c   Open the rails shell
        psql | pg | p       Open the postgres shell
        deploy | d          Push code to remote servers, run migrations, and restart
        restart | r         Restart the remote server
        migrate | m         Run rake db:migrate

    ERROR UNKNOWN COMMAND
    ERROR: UNKNOWN COMMAND
NOTES
  ;;

esac
