#!/bin/bash

if [ -z "$1" -o -z "$2" ]
then
  cat <<USAGE

  USAGE:
    generate-binstubs <repo_dir> <bin_path>

  EXAMPLE:
    generate-binstubs ~/github_repos ~/bin

  ARGS:
    <repo_dir>
      A folder containing 1+ git repos.

    <bin_path>
      Needs to be a folder in your PATH env.

USAGE

  exit 1
fi

function generate_stub() {
  cat <<BINSTUB >"$1/$2"
#!/bin/bash

export APP_NAME="$2"
export APP_DIR="$3"

\$(dirname \$0)/base-binstub \$@
BINSTUB
}


find $1 -name '.git' | while read app
do
  app_dir=$(dirname "${app}")
  app_name=$(basename "${app_dir}")

  echo "Generating binstub for: ${app_name}..."

  generate_stub "$2" "$app_name" "$app_dir"
  chmod +x "$2/$app_name"
done

cp -v "$(dirname $0)/base-binstub" "$2"/

echo "...done"

